# This is a sample build configuration for Gradle.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: therickys93/ubuntu14swiftenv

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - swiftenv install 3.0
          - swiftenv global 3.0
          - swift build
          - swift build -c release